name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - appmode
  - pip
  - pip:
    - absl-py==0.9.0
    - alibi==0.4.0
    - appmode==0.7.0
    - astor==0.8.1
    - attrs==19.3.0
    - backcall==0.1.0
    - beautifulsoup4==4.9.0
    - bleach==3.1.5
    - blis==0.4.1
    - catalogue==1.0.0
    - certifi==2020.4.5.1
    - chardet==3.0.4
    - colorama==0.4.3
    - colorful==0.5.4
    - cycler==0.10.0
    - cymem==2.0.3
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dice-ml==0.2
    - entrypoints==0.3
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - imageio==2.8.0
    - importlib-metadata==1.6.0
    - ipykernel==5.2.1
    - ipython==7.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - Jinja2==2.11.2
    - joblib==0.14.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.3
    - jupyter-core==4.6.3
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.0
    - kiwisolver==1.2.0
    - lime==0.2.0.0
    - Markdown==3.2.1
    - MarkupSafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - murmurhash==1.0.2
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - networkx==2.4
    - notebook==6.0.3
    - numpy==1.18.4
    - opt-einsum==3.2.1
    - packaging==20.4
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pickleshare==0.7.5
    - Pillow==5.4.1
    - plac==1.1.3
    - preshed==3.0.2
    - prettyprinter==0.18.0
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - protobuf==3.11.3
    - Pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - PyWavelets==1.1.1
    - pywinpty==0.5.7
    - pyzmq==19.0.1
    - requests==2.23.0
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - Send2Trash==1.5.0
    - shap==0.35.0
    - six==1.14.0
    - soupsieve==2.0
    - spacy==2.2.4
    - srsly==1.0.2
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - thinc==7.4.0
    - tornado==6.0.4
    - tqdm==4.46.0
    - traitlets==4.3.3
    - urllib3==1.25.9
    - wasabi==0.6.0
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - Werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xgboost==1.0.2
    - zipp==3.1.0
